version: '3.8'

services:
  trading-bot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
    command: ["-log-level=debug"]  # Override default log level here
    tty: true